title: Bootcamp Tutorials
theme: just-the-docs
logo: "/assets/images/logo.png"
color_scheme: light

# GitHub Pages-specific settings
url: "https://0rajnishk.github.io"
baseurl: "/bootcamp"  # Must match repo name

# Navigation
aux_links:
  GitHub: https://github.com/0rajnishk/bootcamp

# Enable search
search_enabled: true

# Enable collections if used
collections:
  docs:
    output: true
    permalink: /:collection/:path/
